# Generated by Django 5.0.2 on 2024-03-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CountryData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("population", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "Country Population Data",
            },
        ),
    ]
