# Generated by Django 5.0.2 on 2024-03-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_countrydata_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=100)),
                ("percentage", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "subject percentage Data",
            },
        ),
        migrations.DeleteModel(
            name="CountryData",
        ),
    ]
