# Generated by Django 5.0.2 on 2024-03-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_file_officedata_delete_studentsdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="file",
        ),
        migrations.AlterModelOptions(
            name="officedata",
            options={"verbose_name_plural": "Username Office Data"},
        ),
        migrations.AddField(
            model_name="officedata",
            name="file",
            field=models.FileField(
                default="path/to/default/file.txt", upload_to="office_data/"
            ),
            preserve_default=False,
        ),
    ]
